2019-04-05 13:20:30,972 ERROR: Exception on /auth/login [GET] [in /home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/osboxes/PycharmProjects/cinema/app/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/osboxes/PycharmProjects/cinema/app/templates/base.html", line 59, in template
    {% endblock %}
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/osboxes/PycharmProjects/cinema/app/templates/auth/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/osboxes/PycharmProjects/cinema/app/templates/base.html", line 59, in template
    {% endblock %}
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/osboxes/PycharmProjects/cinema/venv/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2019-04-05 13:21:49,767 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:23:19,636 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:23:23,437 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:23:44,750 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:23:54,399 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:36:49,570 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:38:22,679 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:38:51,222 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:39:55,718 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-05 13:40:35,311 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-07 01:43:55,169 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-07 07:19:28,914 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-07 12:15:03,629 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
2019-04-07 12:27:07,955 INFO: Microblog startup [in /home/osboxes/PycharmProjects/cinema/app/__init__.py:74]
